### ISSUE TITLE
Passing in options - docs & examples?

### ISSUE THREAD

**Issue by ajmas** [spiritree/vue-orgchart#1]
It would be good to show in the docs how to pass in options, such as for the Ajax support or being able to set `toggleSiblingsResp` property. Taking or two of the examples in the orgchart and showing an equivalent with your library could also be useful?

**Comment by spiritree** [comment]
If you are not in webpack environment,props named by camelCase should be kebab-case.
For example,`toggleSiblingsResp`=>`toggle-siblings-resp`
https://spiritree.github.io/vue-orgchart/#/exportpic

**Comment by ajmas** [comment]
I hadn't understand that. That would be handy clarification. Thanks

**Comment by spiritree** [comment]
https://vuejs.org/v2/guide/components.html#camelCase-vs-kebab-case
That's maybe helpful to you.

**Comment by ajmas** [comment]
Well I was trying:

```    <vo-edit :data="chartData" :draggable="true" :toggle-siblings-resp="true"></vo-edit>
```
and also:

```    <vo-edit :data="chartData" :draggable="true" :toggleSiblingsResp="true"></vo-edit>
```

but that didn't seem to show the siblings indicators

**Comment by spiritree** [comment]
Sorry,it's my fault.
import CSS like this 
`<link href="https://cdn.jsdelivr.net/npm/font-awesome@4.7.0/css/font-awesome.min.css" rel="stylesheet">`
you will see the arrow(indicator)

**Comment by ajmas** [comment]
Actually now that I add the stylesheet I can't actually disable the chevrons. I notice the default is false for `toggleSiblingsResp`, but the chevrons still show.

**Comment by spiritree** [comment]
You mean that the chevrons should be disabled by default,right?
Here the explanation for it.
https://github.com/dabeng/OrgChart/issues/123
https://github.com/dabeng/OrgChart/issues/81

**Comment by spiritree** [comment]
add `:toggleCollapse=false` to disable the chevrons
