### ISSUE TITLE
Trouble Reading Documentation

### ISSUE THREAD

**Issue by dusty** [spiritree/vue-orgchart#32]
Javascript console is showing some error related to bootCode not being defined from docsify.  

![jun 14 2018 4_25 pm - edited](https://user-images.githubusercontent.com/792/41443111-db601966-6fef-11e8-875b-b7dbb5caead5.gif)

**Comment by dusty** [comment]
I've never used docsify so I'm not certain what I'm doing here, however, this seemed to fix the problem in docs/index.html.

I just defined bootCode as an empty string before calling docsify.

```
    var bootCode = ''
    window.$docsify = {
      coverpage: true,
      name: 'vue-orgchart',
      loadSidebar: true,
      loadNavbar: true,
      repo: 'https://github.com/spiritree/vue-orgchart',
      plugins: [
        DemoBoxVue.create(jsResources, cssResources)
      ]
    }

```

**Comment by spiritree** [comment]
Fixed.
Thanks for reminding.
