### ISSUE TITLE
Can i change id

### ISSUE THREAD

**Issue by bosemian** [spiritree/vue-orgchart#36]
How can i change id instead, my id in app

![screen shot 2561-07-16 at 14 11 03](https://user-images.githubusercontent.com/22653043/42746550-7ef178ba-8902-11e8-9f7f-09cd7ba2093c.png)

**Comment by spiritree** [comment]
`<vo-basic :createNode="clickNode"></vo-basic>`

```javascript
clickNode(node, data) {
  node.id = 123
}
```
