### ISSUE TITLE
How can i handle a specific node in a tree?

### ISSUE THREAD

**Issue by boussadjra** [spiritree/vue-orgchart#38]
I would like to implement the following feature - everytime user clicks the node, it will pop a window with the details of the specific node.

I would like to implement something like this:
`<vo-basic @click="showDetails(node)" :data="Tree" :pan="true" :zoom="true"></vo-basic>`

**Comment by spiritree** [comment]
`<vo-basic :createNode="clickNode"></vo-basic>`

```javascript
clickNode(node, data) {
  node.addEventListener('click', () => {
    //todo
  })
}
```
