### ISSUE TITLE
direction bottom to top isn't working

### ISSUE THREAD

**Issue by MaG21** [spiritree/vue-orgchart#5]
Property `direction` is not taking effect. Silently vue-orgchart sets default to `t2b`... It seems that the only direction that works is the default one.

```vue
<vo-basic :data="chartData"
              :direction="b2t"
              :draggable=true>
</vo-basic>
```

Check here: https://jsfiddle.net/udnbt9fg/

**Comment by spiritree** [comment]
When the prop type is String,you should not add `:` as prefix.
just use `direction="b2t"`
https://jsfiddle.net/spiritree/udnbt9fg/2/
