### ISSUE TITLE
nodeTitle option isn't working

### ISSUE THREAD

**Issue by MaG21** [spiritree/vue-orgchart#6]
`nodeTitle` option is not working as expected.

**Comment by spiritree** [comment]
When you work in webpack environment
`<vo-basic :data="chartData" nodeTitle="abc"></vo-basic>`is okay
If you are not in webpack environment,props named by camelCase should be kebab-case.
For example,`nodeTitle`=>`node-title`
https://jsfiddle.net/spiritree/udnbt9fg/1/
