### ISSUE TITLE
Missing html2canvas

### ISSUE THREAD

**Issue by scp-nm** [spiritree/vue-orgchart#7]
Hi there,

I'm using your component (which is working great, thanks) but can't get the export feature to work. Whenever I click the 'Export' button it throws the following error in the console:

`Uncaught TypeError: window.html2canvas is not a function at e.value (vue-orgchart.min.js?f5c3:1)`

I'm using:
- VueJs [2.5.13]
- VueOrgchart [1.1.0]

Many thanks,

Neil

**Comment by spiritree** [comment]
```html
<script src="https://cdn.jsdelivr.net/npm/html2canvas@0.5.0-beta4/dist/html2canvas.min.js"></script>
```
add this in your index.html

**Comment by scp-nm** [comment]
Thanks @spiritree
