### ISSUE TITLE
[Feature] add option for 'allowTaint'

### ISSUE THREAD

**Issue by scp-nm** [spiritree/vue-orgchart#8]
Hi there,

Are you planning on allowing for `allowTaint` (Whether to allow cross-origin images to taint the canvas) to be set on the component? This will be helpful for people who may need to display profile photos (potentially served from another server) in their org charts.

Many thanks.

**Comment by spiritree** [comment]
Here is the demo
https://jsfiddle.net/spiritree/nvb2um4a/

**Comment by scp-nm** [comment]
Thanks - I'll have a play with that way of doing it, much appreciated.
